development:
  adapter: mysql2
  database: temp_metrix
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: temp_metrix_test
  username: root
  password: root
  pool: 5
  timeout: 5000
